# Generated by Django 4.2 on 2023-05-01 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storedevice',
            name='user_client_password_profile',
        ),
    ]
