# Generated by Django 4.1.7 on 2023-04-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password_log_on_user',
            name='BMI',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
