# Generated by Django 3.2 on 2023-05-20 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20230520_1629'),
        ('authenticator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storedevice',
            name='user_profile_token',
        ),
        migrations.RemoveField(
            model_name='storedevice',
            name='username_profile',
        ),
        migrations.RemoveField(
            model_name='userlogintoken',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userlogintoken',
            name='username',
        ),
        migrations.DeleteModel(
            name='Password_log_on_user',
        ),
        migrations.DeleteModel(
            name='StoreDevice',
        ),
        migrations.DeleteModel(
            name='UserLoginToken',
        ),
    ]
