# Generated by Django 4.2 on 2023-04-19 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordstorage',
            name='usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
