# Generated by Django 4.1.7 on 2023-04-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password_log_on_user',
            name='email',
            field=models.EmailField(help_text='abc@efg.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='password_log_on_user',
            name='height',
            field=models.FloatField(help_text='in meters, e.g 1.67'),
        ),
        migrations.AlterField(
            model_name='password_log_on_user',
            name='weight',
            field=models.FloatField(help_text='in kilograms e.g 90kg'),
        ),
    ]
