# Generated by Django 4.2 on 2023-05-01 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storedevice',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='storedevice',
            name='user_client_password_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='password_profile_owner', to='authenticator.password_log_on_user'),
        ),
        migrations.AlterField(
            model_name='storedevice',
            name='user_profile_token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_used', to='authenticator.userlogintoken'),
        ),
        migrations.AlterField(
            model_name='storedevice',
            name='username_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_owner_mum', to='authenticator.registerclient'),
        ),
    ]
