# Generated by Django 4.2 on 2023-04-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0002_alter_passwordstorage_usage_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordstorage',
            name='date_exhausted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
