# Generated by Django 4.1.7 on 2023-04-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0002_alter_password_log_on_user_bmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='password_log_on_user',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
