# Generated by Django 4.2 on 2023-04-15 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authenticator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Unanswered_questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_questions', models.ManyToManyField(related_name='all_unanswered_questions', to='apps.questions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='the_user', to='authenticator.userlogintoken')),
            ],
        ),
        migrations.CreateModel(
            name='Stopped_answering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_question', to='apps.questions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_taking_questions', to='authenticator.userlogintoken')),
            ],
        ),
        migrations.CreateModel(
            name='Question1Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_answered', models.DateTimeField(auto_now_add=True)),
                ('age', models.IntegerField()),
                ('mom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questioned_user', to='authenticator.userlogintoken')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_storage', to='apps.questions')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_questioned_user', to='authenticator.userlogintoken')),
                ('username_used', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_owner', to='authenticator.userlogintoken')),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('user_diagonised', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_disease', to='authenticator.userlogintoken')),
            ],
        ),
        migrations.CreateModel(
            name='Answered_questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.ManyToManyField(related_name='all_answered_questions', to='apps.questions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='the_user_answered', to='authenticator.userlogintoken')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_to_ask', to='apps.questions')),
                ('user_print', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_in_question', to='authenticator.userlogintoken')),
            ],
        ),
    ]
