# Generated by Django 4.2 on 2023-04-30 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authenticator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ResultOfTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Question1Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_answered', models.DateTimeField(auto_now_add=True)),
                ('age', models.IntegerField()),
                ('mom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questioned_user', to='authenticator.userlogintoken')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_storage', to='apps.questions')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_questioned_user', to='authenticator.userlogintoken')),
                ('username_used', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_owner', to='authenticator.userlogintoken')),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('user_diagnosed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_disease', to='authenticator.userlogintoken')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_to_ask', to='apps.questions')),
                ('user_print', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_in_question', to='authenticator.userlogintoken')),
            ],
        ),
    ]
