# Generated by Django 3.2 on 2023-05-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mom_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('browser', models.CharField(max_length=100)),
                ('device_token', models.CharField(max_length=100)),
                ('app_password', models.CharField(max_length=100)),
                ('client_reference', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='user_print',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='verified',
        ),
        migrations.AlterField(
            model_name='disease',
            name='user_diagnosed',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question1model',
            name='mom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question1model',
            name='token',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question1model',
            name='username_used',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question2model',
            name='token',
            field=models.CharField(max_length=200),
        ),
    ]
