# Generated by Django 3.2 on 2023-05-07 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0001_initial'),
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Question2Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_answered', models.DateTimeField(auto_now_add=True)),
                ('height', models.FloatField(help_text='in cms')),
                ('weight', models.FloatField(help_text='in kgs')),
                ('BMI', models.CharField(max_length=20)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_storage_q2', to='apps.questions')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_questioned_user_q2', to='authenticator.userlogintoken')),
            ],
        ),
    ]
