# Generated by Django 4.2 on 2023-04-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultOfTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='stopped_answering',
            name='current_stop',
        ),
        migrations.RemoveField(
            model_name='stopped_answering',
            name='user',
        ),
        migrations.RemoveField(
            model_name='unanswered_questions',
            name='all_questions',
        ),
        migrations.RemoveField(
            model_name='unanswered_questions',
            name='user',
        ),
        migrations.RenameField(
            model_name='disease',
            old_name='user_diagonised',
            new_name='user_diagnosed',
        ),
        migrations.DeleteModel(
            name='Answered_questions',
        ),
        migrations.DeleteModel(
            name='Stopped_answering',
        ),
        migrations.DeleteModel(
            name='Unanswered_questions',
        ),
    ]
