# Generated by Django 3.2 on 2023-06-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=30)),
                ('patient', models.CharField(max_length=40)),
                ('answer', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
    ]
