# Generated by Django 3.2 on 2024-01-07 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_saveanwerstemporarily'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mom_data',
            old_name='device_token',
            new_name='token',
        ),
    ]
